theme = "habamax"

[editor]
line-number = "relative"
continue-comments = false
completion-timeout = 5
completion-trigger-len = 2
popup-border = "all"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-base-name", "version-control"]
right = ["diagnostics", "position", "register"]
