theme = "any"

[editor]
line-number = "relative"
continue-comments = false
completion-timeout = 5
completion-trigger-len = 2
popup-border = "all"
color-modes = true

[editor.lsp]
enable = true
display-messages = false
auto-signature-help = true
display-signature-help-docs = false

[editor.statusline]
left = ["mode", "spinner", "version-control", "diagnostics"]
center = ["file-base-name"]
right = ["position", "register"]
