theme = "cyberdream"

[editor]
line-number = "relative"
end-of-line-diagnostics = "hint"
popup-border = "all"
completion-timeout = 5
completion-replace = false


[editor.inline-diagnostics]
cursor-line = "warning"

