"ui.background" = "fg" 
"ui.text" = "fg"
"ui.text.focus" = { bg = "bg_highlight", fg = "cyan" }
"ui.cursor" = { bg = "magenta", fg = "bg" }
"ui.linenr" = "grey"
"ui.statusline" = { fg = "baby_blue" }
"ui.selection" = { bg = "bg_highlight" } 
"ui.selection.primary" = { bg = "bg_highlight" }  
"ui.virtual.ruler" = { bg = "bg_highlight" }

# Markdown Highlighting
"markup.raw" = { fg = "magenta", bg = "bg" } 
"markup.raw.inline" = { fg = "orange" } 
"markup.heading.1" = { fg = "cyan", bg = "#2F4456" }
"markup.heading.2" = { fg = "magenta", bg = "#6B4E6D" } 
"markup.heading.3" = { fg = "green", bg = "#3C453D" }
"markup.heading.4" = { fg = "yellow", bg = "#7A6A5D" }
"markup.heading.5" = { fg = "orange", bg = "#7A4B3A" }
"markup.heading.6" = { fg = "cyan", bg = "#2F4456" }

"markup.list" = { fg = "magenta" }
"markup.bold" = { fg = "orange", modifiers = ["bold"] }
"markup.italic" = { fg = "orange" }
"markup.strikethrough" = { fg = "red", modifiers = ["crossed_out"] }
"markup.link" = { fg = "cyan" }
"markup.quote" = { fg = "fg" }

# Syntax Highlighting for Code
"comment" = { fg = "grey" }
"comment.line" = { fg = "grey" }
"comment.block" = { fg = "grey" }
"comment.documentation" = { fg = "blue" }

"keyword" = "cyan"
"keyword.control" = "cyan"
"keyword.operator" = "fg"
"keyword.function" = "cyan"
"keyword.directive" = "green"
"keyword.storage" = "cyan"

"type" = "orange"
"type.builtin" = "cyan" 
"type.enum.variant" = "fg"

"function" = "yellow"
"function.builtin" = "fg"
"function.method" = "yellow"
"function.macro" = "fg"

"variable" = "purple"
"variable.builtin" = "fg"
"variable.parameter" = "fg" 

"string" = "magenta"
"string.special" = "magenta"

"constant" = "fg"
"constant.builtin" = "yellow"
"constant.numeric" = "yellow"
"constant.character" = "yellow"
"constant.boolean" = "fg"

"attribute" = "magenta"
"operator" = "fg"
"tag" = { fg = "magenta", modifiers = ["bold"] }
"tag.special" = { fg = "orange", modifiers = ["bold"] }
"namespace" = "fg"
"macro" = "orange"
"label" = "red"

# Interface specific
"ui.cursorline.primary" = { bg = "bg_highlight" }
"ui.cursorline.secondary" = { bg = "bg_alt" }
"ui.cursorcolumn.primary" = { bg = "bg_highlight" }
"ui.cursorcolumn.secondary" = { bg = "bg_alt" }
"ui.statusline.normal" = { fg = "bg", bg = "baby_blue" }
"ui.statusline.insert" = { fg = "bg", bg = "green" }
"ui.statusline.select" = { fg = "bg", bg = "magenta" }

# Diagnostic styles
"warning" = { fg = "yellow", modifiers = ["bold"] }
"error" = { fg = "red", modifiers = ["bold"] }
"info" = { fg = "cyan", modifiers = ["bold"] }
"hint" = { fg = "blue", modifiers = ["bold"] }
"diagnostic.error" = { fg = "red" }
"diagnostic.warning" = { fg = "yellow" }
"diagnostic.info" = { fg = "cyan" }
"diagnostic.hint" = { fg = "blue" }

# Popups for documentation or file picker
"ui.popup" = { fg = "fg", bg = "bg" } 
"ui.popup.info" = { fg = "fg", bg = "bg" } 
"ui.menu" = { fg = "fg", bg = "bg" } 
"ui.menu.selected" = { fg = "cyan", bg = "bg_highlight" }


# Additional overrides
"ui.virtual.whitespace" = "grey"
"ui.virtual.indent-guide" = { fg = "grey", style = "dotted" }

[palette]
bg = "#181818"
fg = "#d6d6dd" 
grey = "#6D6D6D"
blue = "#4A90E2"
green = "#A7CB7B"
cyan = "#82D2CE" 
red = "#BF7F88"
yellow = "#E9C78C"
magenta = "#D78CD0"
purple = "#A899F2"
orange = "#EFB080" 
bg_alt = "#2A2A2A"
bg_highlight = "#3c4048"
baby_blue = "#94C0F9"
