# --------------------------
# INTERFACE
# --------------------------

"ui.background" = { bg = "bg1" }
"ui.gutter" = { fg = "fg3" }

"ui.text" = { fg = "fg1" }
"ui.text.directory" = { fg = "blue-bright" }
"ui.text.focus" = { bg = "sel1", fg = "fg1" }
"ui.text.info" = { fg = "fg2", bg = "bg1" }

"ui.cursor" = { bg = "fg3", fg = "bg1" }
"ui.cursor.primary" = { bg = "fg1", fg = "bg1" }
"ui.cursor.match" = { fg = "yellow", modifiers = ["bold"] }

"ui.selection" = { bg = "bg4" }
"ui.selection.primary" = { bg = "sel1" }
"ui.cursorline.primary" = { bg = "bg3" }

"ui.linenr" = { fg = "fg3" }
"ui.linenr.selected" = { fg = "yellow", modifiers = ["bold"] }

"ui.virtual.ruler" = { bg = "bg3" }
"ui.virtual.whitespace" = { fg = "bg3" }
"ui.virtual.indent-guide" = { fg = "black" }
"ui.virtual.inlay-hint" = { fg = "comment", bg = "bg2" }
"ui.virtual.jump-label" = { fg = "blue", modifiers = ["bold"] }

"ui.statusline" = { fg = "fg2", bg = "bg1" }
"ui.statusline.inactive" = { fg = "fg3", bg = "bg0" }
"ui.statusline.normal" = { bg = "blue", fg = "bg0", modifiers = ["bold"] }
"ui.statusline.insert" = { bg = "green", fg = "bg0", modifiers = ["bold"] }
"ui.statusline.select" = { bg = "magenta", fg = "bg0", modifiers = ["bold"] }

"ui.menu" = { bg = "bg1", fg = "fg1" }
"ui.menu.selected" = { bg = "fg3" }
"ui.popup" = { bg = "bg1", fg = "fg1" }
"ui.popup.info" = { bg = "bg1", fg = "fg1" }

# --------------------------
# MARKUP
# --------------------------

"markup.raw" = { fg = "blue", bg = "bg" } 
"markup.raw.inline" = { fg = "orange-bright" } 
"markup.heading.1" = { fg = "magenta-bright", bg = "bg1"}
"markup.heading.2" = { fg = "blue-bright", bg = "bg1" }
"markup.heading.3" = { fg = "cyan-bright", bg = "bg1" }
"markup.heading.4" = { fg = "orange-bright", bg = "bg1" }
"markup.heading.5" = { fg = "yellow-bright", bg = "bg1" }
"markup.heading.6" = { fg = "pink-bright", bg = "bg1" }
"markup.list" = { fg = "magenta" }
"markup.bold" = { fg = "yellow-bright", modifiers = ["bold"] }
"markup.italic" = { fg = "comment" }
"markup.strikethrough" = { fg = "red-bright", modifiers = ["crossed_out"] }
"markup.link" = { fg = "cyan-bright" }
"markup.quote" = { fg = "comment" }

# --------------------------
# DIAGNOSTICS
# --------------------------

"warning" = { fg = "yellow", bg = "bg1" }
"error" = { fg = "red", bg = "bg1" }
"info" = { fg = "blue", bg = "bg1" }
"hint" = { fg = "green", bg = "bg1" }

"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.hint" = { underline = { color = "green", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

# --------------------------
# SYNTAX (MINIMAL)
# --------------------------
"keyword" = { fg = "magenta" }
"keyword.control" = { fg = "magenta" }
"keyword.control.conditional" = { fg = "magenta" }
"keyword.control.repeat" = { fg = "magenta" }
"keyword.control.import" = { fg = "magenta" }
"keyword.control.return" = { fg = "magenta" }
"keyword.control.exception" = { fg = "magenta" }
"keyword.function" = { fg = "magenta" }
"keyword.storage" = { fg = "magenta" }
"keyword.storage.type" = { fg = "magenta" }

"function" = { fg = "blue" }
"function.builtin" = { fg = "blue" }

"type" = { fg = "yellow" }
"type.builtin" = { fg = "yellow" }

"constant.numeric"  = { fg = "orange" }

"string" = { fg = "green" }

"comment" = { fg = "fg3" }

# --------------------------
# DIFF (unchanged)
# --------------------------

"diff.plus" = "green"
"diff.minus" = "red"
"diff.delta" = "blue"
"diff.delta.moved" = "cyan"

# --------------------------
# COLOR PALETTE
# --------------------------

[palette]
black          = "#393b44"
red            = "#c94f6d"
red-dim        = "#2f2837"
green          = "#81b29a"
green-dim      = "#26343c"
yellow         = "#dbc074"
yellow-bright  = "#e0c989"
blue           = "#719cd6"
blue-bright    = "#86abdc"
blue-dim       = "#2f2837"
magenta        = "#9d79d6"
magenta-bright = "#baa1e2"
cyan           = "#63cdcf"
cyan-bright    = "#7ad4d6"
cyan-dim       = "#253f4a"
white          = "#dfdfe0"
orange         = "#f4a261"
orange-bright  = "#f6b079"
pink           = "#d67ad2"
pink-bright    = "#dc8ed9"
comment        = "#738091"

bg0            = "#131a24"
bg1            = "#192330"
bg2            = "#212e3f"
bg3            = "#29394f"
bg4            = "#39506d"
fg0            = "#d6d6d7"
fg1            = "#cdcecf"
fg2            = "#aeafb0"
fg3            = "#71839b"
sel0           = "#2b3b51"
sel1           = "#3c5372"

