# UI Elements
"ui.background" = { fg = "fg", bg = "bg" }
"ui.text" = "fg"
"ui.text.focus" = { fg = "bg", bg = "fg" }
"ui.cursor" = { bg = "blue", fg = "bg" }
"ui.linenr" = { fg = "fg-gutter" }
"ui.linenr.selected" = { fg = "yellow" }
"ui.selection" = { bg = "bg-selection" }
"ui.selection.primary" = { bg = "bg-selection" }

# Interface specific
"ui.cursorline.primary" = { bg = "bg-menu" }
"ui.cursorline.secondary" = { bg = "bg-menu" }
"ui.cursorcolumn.primary" = { bg = "bg-menu" }
"ui.cursorcolumn.secondary" = { bg = "bg-menu" }

# Status line
"ui.statusline" = { fg = "fg-dark", bg = "bg" }
"ui.statusline.normal" = { fg = "bg", bg = "blue", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "bg", bg = "light-green", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "bg", bg = "magenta", modifiers = ["bold"] }
"ui.virtual.whitespace" = "fg-gutter"
"ui.virtual.ruler" = { bg = "fg-gutter" }

# Popups and Menus
"ui.popup" = { fg = "fg", bg = "bg" }
"ui.popup.info" = { fg = "fg", bg = "bg" }
"ui.menu" = { fg = "fg", bg = "bg" }
"ui.menu.selected" = { fg = "bg", bg = "fg" }

# Comments
"comment" = { fg = "comment" }

# Keywords
"keyword" = "purple"

# Types
"type" = "aqua"
"type.builtin" = "aqua"
"type.parameter" = "aqua"
"type.enum" = "aqua"

# Functions
"function" = "blue"
"function.builtin" = "aqua"
"function.macro" = "cyan"

# Variables
"variable" = "fg"
"variable.builtin" = "red"
"variable.parameter" = "fg"

# Constants
"constant" = "orange"
"constant.builtin" = "aqua"
"constant.character" = "light-green"
"constant.numeric" = "orange"

# Strings
"string" = "light-green"

# Operators / Punctuation
"operator" = "fg"
"punctuation" = "fg"

# Tags / Attributes
"tag" = "magenta"
"attribute" = "cyan"

# Markdown / Markup
"markup.heading" = { fg = "blue", modifiers = ["bold"] }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link" = { fg = "blue", underline = { style = "line" } }
"markup.list" = { fg = "orange" }
"markup.raw" = { fg = "teal" }

# Diagnostics
"error" = { fg = "error", modifiers = ["bold"] }
"warning" = { fg = "yellow", modifiers = ["bold"] }
"info" = { fg = "info", modifiers = ["bold"] }
"hint" = { fg = "hint", modifiers = ["bold"] }
"diagnostic.error" = { fg = "comment" }
"diagnostic.warning" = { fg = "comment" }
"diagnostic.info" = { fg = "comment" }
"diagnostic.hint" = { fg = "comment" }

# Git Diffs
"diff.plus" = "light-green"
"diff.minus" = "red"
"diff.delta" = "blue"

[palette]
red = "#f7768e"
orange = "#ff9e64"
yellow = "#e0af68"
light-green = "#9ece6a"
green = "#73daca"
aqua = "#2ac3de"
teal = "#1abc9c"
cyan = "#7dcfff"
blue = "#7aa2f7"
purple = "#9d7cd8"
magenta = "#bb9af7"
comment = "#565f89"
black = "#414868"

add = "#449dab"
change = "#6183bb"
delete = "#914c54"

error = "#db4b4b"
info = "#0db9d7"
hint = "#1abc9c"

fg = "#c0caf5"
fg-dark = "#a9b1d6"
fg-gutter = "#3b4261"
fg-linenr = "#737aa2"
fg-selected = "#343a55"
border = "#15161e"
border-highlight = "#27a1b9"
bg = "#1a1b26"
bg-inlay = "#1a2b32"
bg-selection = "#283457"
bg-menu = "#16161e"
bg-focus = "#292e42"
