"ui.background" = "fg" 
 "ui.text" = "fg"
 "ui.text.focus" = { bg = "bg_highlight", fg = "cyan" } 
 "ui.cursor" = { bg = "fg", fg = "bg" }
 "ui.linenr" = "grey"
 "ui.statusline" = { fg = "blue" }
 "ui.selection" = { bg = "bg_highlight" } 
 
 # Markdown highlighting
 "markup.raw" = { fg = "purple", bg = "bg" } 
 "markup.raw.inline" = { fg = "red" } 
 "markup.heading.marker" = { fg = "blue" }
 "markup.list" = { fg = "purple" }
 "markup.bold" = { fg = "red", modifiers = ["bold"] }
 "markup.italic" = { fg = "red" }
 "markup.strikethrough" = { fg = "red", modifiers = ["crossed_out"] }
 "markup.link" = { fg = "cyan" }
 "markup.quote" = { fg = "fg" }
 
 # Syntax Highlighting for Code
 "comment" = { fg = "grey", modifiers = ["italic"] }
 "comment.line" = { fg = "grey", modifiers = ["italic"] }
 "comment.block" = { fg = "grey", modifiers = ["italic"] }
 "comment.documentation" = { fg = "blue", modifiers = ["italic"] }
 "keyword" = "orange"
 "keyword.control" = "orange"
 "keyword.operator" = "red"
 "keyword.function" = "orange"
 "type" = "blue"
 "type.builtin" = "fg" 
 "function" = "blue"
 "function.builtin" = "red"
 "function.method" = "blue"
 "variable" = "fg"
 "variable.builtin" = "purple"
 "variable.parameter" = "fg"
 "string" = "green"
 "string.special" = "red"
 "constant" = "fg"
 "constant.builtin" = "red"
 "constant.numeric" = "orange"
 "constant.character" = "red"
 "constant.boolean" = "red"
 "attribute" = "purple"
 "operator" = "cyan"
 "tag" = { fg = "purple", modifiers = ["bold"] }
 "tag.special" = { fg = "orange", modifiers = ["bold"] }
 "namespace" = "purple"
 "macro" = "orange"
 "label" = "red"
 
 # Interface specific
 "ui.cursorline.primary" = { bg = "bg_highlight" }
 "ui.cursorline.secondary" = { bg = "bg_alt" }
 "ui.cursorcolumn.primary" = { bg = "bg_highlight" }
 "ui.cursorcolumn.secondary" = { bg = "bg_alt" }
 "ui.statusline.normal" = { fg = "fg", bg = "bg" }
 "ui.statusline.insert" = { fg = "green", bg = "bg" }
 "ui.statusline.select" = { fg = "blue", bg = "bg" }
 "ui.statusline.command" = { fg = "red", bg = "bg" }
 "ui.statusline.visual" = { fg = "purple", bg = "bg" }
 
 # Diagnostic styles
 "warning" = { fg = "yellow", modifiers = ["bold"] }
 "error" = { fg = "red", modifiers = ["bold"] }
 "info" = { fg = "cyan", modifiers = ["bold"] }
 "hint" = { fg = "blue", modifiers = ["bold"] }
 "diagnostic.error" = { fg = "red" }
 "diagnostic.warning" = { fg = "yellow" }
 "diagnostic.info" = { fg = "cyan" }
 "diagnostic.hint" = { fg = "blue" }
 
 # Popups for documentation or file picker
 "ui.popup" = { fg = "fg", bg = "bg" }
 "ui.popup.info" = { fg = "fg", bg = "bg" }
 "ui.menu" = { fg = "fg", bg = "bg" }
 "ui.menu.selected" = { fg = "cyan", bg = "bg_highlight" }
 
 [palette]
 bg = "#1d1f21"                
 fg = "#c5c8c6"                
 grey = "#969896"              
 blue = "#81a2be"              
 green = "#b5bd68"             
 cyan = "#8abeb7"              
 red = "#cc6666"               
 yellow = "#f0c674"            
 purple = "#b294bb"
 orange = "#de935f"            
 bg_highlight = "#373b41"      
 bg_alt = "#282a2e"            
 
